package by.academy.it.task13.controller.admin;

public class AdminConstant {
    public static final String ADMIN_MAIN_MAPPING = "/admin";
    public static final String TITLE = "title";

    public static final String ADMIN_MAIN_PAGE = "admin/main";
    public static final String MENU_ADMIN_MAIN_MESSAGE = "menu_admin.main";
    public static final String ADMIN_CERTIFICATE_TYPE_MAPPING = "/admin/certificatetype";
    public static final String ADMIN_GIFT_CERTIFICATE_MAPPING = "/admin/certificate";
    public static final String ADMIN_GIFT_CERTIFICATE_ORDER_MAPPING = "/admin/certificateorder";
    public static final String ADMIN_HORSE_MAPPING = "/admin/horse";
    public static final String ADMIN_COACH_MAPPING = "/admin/coach";
    public static final String ADMIN_PHOTO_SESSION_MAPPING = "/admin/photosession";
    public static final String ADMIN_SETTING_MAPPING = "/admin/setting";
    public static final String ADMIN_CERTIFICATE_DECORATION_MAPPING = "/admin/certificatedecoration";
    public static final String MENU_ADMIN_CERTIFICATE_TYPE_MESSAGE = "menu_admin.certificate_type";
    public static final String MENU_ADMIN_CERTIFICATE_ORDER_MESSAGE = "menu_admin.certificate_order";
    public static final String MENU_ADMIN_GIFT_CERTIFICATE_MESSAGE = "menu_admin.certificate";
    public static final String MENU_ADMIN_CERTIFICATE_DECORATION_MESSAGE = "menu_admin.certificate_decoration";
    public static final String MENU_ADMIN_HORSE_MESSAGE = "menu_admin.horses";
    public static final String MENU_ADMIN_COACH_MESSAGE = "menu_admin.coaches";
    public static final String MENU_ADMIN_UPLOAD_MESSAGE = "menu_admin.upload";
    public static final String MENU_ADMIN_PHOTO_SESSION_MESSAGE = "menu_admin.photosession";
    public static final String MENU_ADMIN_SETTING_MESSAGE = "menu_admin.setting";
    public static final String ADMIN_CERTIFICATE_ORDER_PAGE = "admin/certificate_order";
    public static final String ADMIN_GIFT_CERTIFICATE_PAGE = "admin/certificate";
    public static final String ADMIN_CERTIFICATE_TYPE_PAGE = "admin/certificate_type";
    public static final String ADMIN_CERTIFICATE_DECORATION_PAGE = "admin/certificate_decoration";
    public static final String ADMIN_HORSE_PAGE = "admin/horse";
    public static final String ADMIN_COACH_PAGE = "admin/coach";
    public static final String ADMIN_PHOTO_SESSION_PAGE = "admin/photosession";
    public static final String CERTIFICATE_TYPE_LIST = "certificateTypeList";
    public static final String CERTIFICATE_DECORATION_LIST = "certificateDecorationList";
    public static final String HORSE_LIST = "horseList";
    public static final String COACH_LIST = "coachList";
    public static final String ATTACHMENT_LIST = "attachmentList";
    public static final String IMAGE_FILE_LIST = "imageFileList";
    public static final String PHOTO_SESSION_LIST = "photosessionList";
    public static final String ACTIVE_USER_LIST = "activeUserList";
    public static final String ORDER_STATUS_LIST = "orderStatusList";
    public static final String GIFT_CERTIFICATE_LIST = "giftCertificateList";
    public static final String CERTIFICATE_ORDER_PAGE = "certificateOrderPage";
    public static final String DELETE_MAPPING = "/delete";
    public static final String SORT_FIELD = "sortField";
    public static final String SORT_DIRECTION = "sortDirection";
    public static final String REVERSE_SORT_DIRECTION = "reverseSortDirection";
    public static final String ASC = "asc";
    public static final String DESC = "desc";
}
